### ISSUE TITLE
Impliment ActivityPub protocol

### ISSUE THREAD

**Issue by TrashMacNugget** [OpenBookOrg/ideas#1]
[ActivityPub](https://activitypub.rocks) is a decentralized social network protocol already in use by 1 million+ users, used by Mastodon. This would make it easier for Openbook to take off, as it would already have a significant userbase when it started.

**Comment by lifenautjoe** [comment]
Hello again @TrashMacNugget !

We will look into this asap.

Something to keep in mind though is that we aim to be [GDPR](https://www.eugdpr.org/) compliant, in this context, we must be able to provide users an exact location of their data and a way to delete it, even from third parties.

Decentralised networks, by design don't allow this kind of behaviour. 

For an example, see ["You can't delete your mastodon account"](https://mashable.com/2017/04/06/you-cant-delete-your-mastodon-account/#Ys6ycutNiSqZ).

Cheers!

**Comment by lifenautjoe** [comment]
Hi @TrashMacNugget ,

We have gone through the protocol and sadly we must inform you that we do not intend to support this from conception. 

We want to give our users absolute control of their data. We want them to be able to see the exact physical location of their data and to be able to delete it, even when shared with third party applications.

Protocols for interconnection between social networks such as ActivityPub rely on distributed networks to accomplish this. These networks, by design being immutable, thing which make the previous items impossible to accomplish.

Don't get us wrong, we love the idea. Perhaps when we are more mature we can can work with the open source community to build something that allows for social network interoperability, while giving it's users control of their data.


Thank you again for bringing this up, it raised interesting questions and will have a positive impact in our planning.
